site_name: PyMADS Documentation
site_url: https://github.com/pkali/pymads
repo_url: https://github.com/pkali/pymads
repo_name: pkali/pymads

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - footnotes
  - def_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google

nav:
  - Home: index.md
  - Codebase Analysis:
    - Structure Overview: codebase_analysis/structure_overview.md
    - Core Functions: codebase_analysis/core_functions.md
  - Development:
    - Setup Guide: development/setup.md
    - Contributing: development/contributing.md
  - Tools:
    - Binary Comparison: tools/binary_comparison.md
  - API Reference: api/
